project:
  type: website
  output-dir: _site

website:
  title: "Calypso QEMU"
  search:
    location: sidebar
    type: textbox
  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - text: "Index"
        href: index.qmd
      - section: "1 - Documentation"
        contents:
          - href: sec1-01.qmd
            text: "partie 1"
      - section: "2 - Tests"
        contents:
          - href: sec2-01.qmd
            text: "partie 1"
      - section: "3 - Headers"
        contents:
          - href: sec3-01.qmd
            text: "partie 1"
      - section: "4 - Sources"
        contents:
          - href: sec4-01.qmd
            text: "partie 1"
      - section: "5 - Python"
        contents:
          - href: sec5-01.qmd
            text: "partie 1"
          - href: sec5-02.qmd
            text: "partie 2"
      - section: "6 - Shell"
        contents:
          - href: sec6-01.qmd
            text: "partie 1"
          - href: sec6-02.qmd
            text: "partie 2"
          - href: sec6-03.qmd
            text: "partie 3"

format:
  html:
    theme: [sketchy]
    css: sketchy.css
    toc: true
    toc-depth: 2
    toc-location: right
    toc-title: "Fichiers"
    number-sections: false
    anchor-sections: true
    smooth-scroll: true
    code-copy: true
    code-overflow: scroll
    code-block-bg: true
    highlight-style: arrow
    embed-resources: false
    include-after-body: sk-filter.html
    mermaid:
      theme: neutral
